trigger:
  branches:
    include:
      - v2
  paths:
    exclude:
      - README.md
pr:
  branches:
    include:
      - v2
  paths:
    exclude:
      - README.md
pool:
  vmImage: "ubuntu-latest"
variables:
  GOPATH: "$(system.defaultWorkingDirectory)/gopath"
  GOROOT: "/opt/hostedtoolcache/go/1.12.0"
  modulePath: "$(GOPATH)/src/github.com/$(build.repository.name)"
  GO111MODULE: "on"
steps:
  - task: GoTool@0
    inputs:
      version: 1.12
    displayName: "Use Go 1.12"
  - script: |
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      mv !(gopath) $(modulePath)
    displayName: "Setup"
  - task: Go@0
    inputs:
      command: "build"
      arguments: "-mod=vendor"
      workingDirectory: "$(modulePath)"
    displayName: "Build"
  - task: Docker@2
    inputs:
      command: login
      containerRegistry: dockerhub
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    displayName: Login to Docker Hub
  - task: Docker@2
    inputs:
      command: buildAndPush
      repository: imlonghao/smms-bot
      tags: latest
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    displayName: Build and Push